// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UpSkillApi.Data;

#nullable disable

namespace UpSkillApi.Migrations
{
    [DbContext(typeof(UpSkillDbContext))]
    [Migration("20250422185346_ooiiee")]
    partial class ooiiee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UpSkillApi.Models.Advertisement", b =>
                {
                    b.Property<int>("AdvertisementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdvertisementId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SponsorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Value")
                        .HasColumnType("int");

                    b.HasKey("AdvertisementId");

                    b.HasIndex("SponsorId");

                    b.ToTable("Advertisements");
                });

            modelBuilder.Entity("UpSkillApi.Models.ApplicationStatus", b =>
                {
                    b.Property<int>("ApplicationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationStatusId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ApplicationStatusId");

                    b.ToTable("ApplicationStatuses");

                    b.HasData(
                        new
                        {
                            ApplicationStatusId = 1,
                            CreatedDate = new DateTime(2025, 4, 22, 18, 53, 46, 144, DateTimeKind.Utc).AddTicks(1830),
                            Description = "Awaiting review",
                            Status = 1
                        },
                        new
                        {
                            ApplicationStatusId = 2,
                            CreatedDate = new DateTime(2025, 4, 22, 18, 53, 46, 144, DateTimeKind.Utc).AddTicks(1840),
                            Description = "Application accepted",
                            Status = 2
                        },
                        new
                        {
                            ApplicationStatusId = 3,
                            CreatedDate = new DateTime(2025, 4, 22, 18, 53, 46, 144, DateTimeKind.Utc).AddTicks(1840),
                            Description = "Application denied",
                            Status = 3
                        });
                });

            modelBuilder.Entity("UpSkillApi.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrontNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("UpSkillApi.Models.ClientPost", b =>
                {
                    b.Property<int>("ClientPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientPostId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .HasMaxLength(2550)
                        .HasColumnType("nvarchar(2550)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ClientPostId");

                    b.HasIndex("ClientId");

                    b.HasIndex("PostStatusId");

                    b.HasIndex("ProfessionId");

                    b.ToTable("ClientPosts");
                });

            modelBuilder.Entity("UpSkillApi.Models.Organization", b =>
                {
                    b.Property<int>("OrganizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrganizationId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DocumentationPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationRole")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrganizationId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("UpSkillApi.Models.PaidJob", b =>
                {
                    b.Property<int>("PaidJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaidJobId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsManuallyClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfPeopleNeeded")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaidJobId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PostStatusId");

                    b.ToTable("PaidJobs");
                });

            modelBuilder.Entity("UpSkillApi.Models.PostStatus", b =>
                {
                    b.Property<int>("PostStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostStatusId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PostStatusId");

                    b.ToTable("PostStatuses");

                    b.HasData(
                        new
                        {
                            PostStatusId = 1,
                            Description = "The post is publicly visible",
                            Name = "Posted"
                        },
                        new
                        {
                            PostStatusId = 2,
                            Description = "The job is completed or closed",
                            Name = "Done"
                        });
                });

            modelBuilder.Entity("UpSkillApi.Models.Profession", b =>
                {
                    b.Property<int>("ProfessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProfessionId");

                    b.ToTable("Professions");

                    b.HasData(
                        new
                        {
                            ProfessionId = 1,
                            Name = "نجار"
                        },
                        new
                        {
                            ProfessionId = 2,
                            Name = "سباك"
                        },
                        new
                        {
                            ProfessionId = 3,
                            Name = "كهربائي"
                        },
                        new
                        {
                            ProfessionId = 4,
                            Name = "حداد"
                        },
                        new
                        {
                            ProfessionId = 5,
                            Name = "نقاش"
                        },
                        new
                        {
                            ProfessionId = 6,
                            Name = "عامل بناء"
                        },
                        new
                        {
                            ProfessionId = 7,
                            Name = "فني رخام"
                        },
                        new
                        {
                            ProfessionId = 8,
                            Name = "فني سيراميك"
                        },
                        new
                        {
                            ProfessionId = 9,
                            Name = "خياطة"
                        },
                        new
                        {
                            ProfessionId = 10,
                            Name = "سجاد يدوي"
                        },
                        new
                        {
                            ProfessionId = 11,
                            Name = "حفر علي الخشب"
                        },
                        new
                        {
                            ProfessionId = 12,
                            Name = "كروشيه و تريكوه"
                        },
                        new
                        {
                            ProfessionId = 13,
                            Name = "تطريز يدوي"
                        },
                        new
                        {
                            ProfessionId = 14,
                            Name = "اكسسوارات يدوية"
                        },
                        new
                        {
                            ProfessionId = 15,
                            Name = "صناعة شموع"
                        },
                        new
                        {
                            ProfessionId = 16,
                            Name = "صناعة فخار"
                        },
                        new
                        {
                            ProfessionId = 17,
                            Name = "الرسم"
                        },
                        new
                        {
                            ProfessionId = 18,
                            Name = "الرسم علي الزجاج"
                        },
                        new
                        {
                            ProfessionId = 19,
                            Name = "أخرى"
                        });
                });

            modelBuilder.Entity("UpSkillApi.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("RatingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("UpSkillApi.Models.Sponsor", b =>
                {
                    b.Property<int>("SponsorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SponsorId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SponsorId");

                    b.ToTable("Sponsors");
                });

            modelBuilder.Entity("UpSkillApi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Points")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UpSkillApi.Models.VolunteeringApplication", b =>
                {
                    b.Property<int>("VolunteeringApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteeringApplicationId"));

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VolunteeringJobId")
                        .HasColumnType("int");

                    b.Property<int?>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("VolunteeringApplicationId");

                    b.HasIndex("ApplicationStatusId");

                    b.HasIndex("ClientId");

                    b.HasIndex("VolunteeringJobId");

                    b.HasIndex("WorkerId");

                    b.ToTable("VolunteeringApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.VolunteeringJob", b =>
                {
                    b.Property<int>("VolunteeringJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VolunteeringJobId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumberOfPeopleNeeded")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<int>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("VolunteeringJobId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PostStatusId");

                    b.ToTable("VolunteeringJobs");
                });

            modelBuilder.Entity("UpSkillApi.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BackNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClearanceCertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Experience")
                        .HasColumnType("int");

                    b.Property<string>("FrontNationalIdPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProfessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WorkerId");

                    b.HasIndex("NationalId")
                        .IsUnique();

                    b.HasIndex("ProfessionId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("UpSkillApi.Models.WorkerApplication", b =>
                {
                    b.Property<int>("WorkerApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkerApplicationId"));

                    b.Property<int>("ApplicationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ApplyDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ClientPostId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PaidJobId")
                        .HasColumnType("int");

                    b.Property<int>("WorkerId")
                        .HasColumnType("int");

                    b.HasKey("WorkerApplicationId");

                    b.HasIndex("ApplicationStatusId");

                    b.HasIndex("ClientPostId");

                    b.HasIndex("PaidJobId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.Advertisement", b =>
                {
                    b.HasOne("UpSkillApi.Models.Sponsor", "Sponsor")
                        .WithMany("Advertisements")
                        .HasForeignKey("SponsorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Sponsor");
                });

            modelBuilder.Entity("UpSkillApi.Models.Client", b =>
                {
                    b.HasOne("UpSkillApi.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("UpSkillApi.Models.Client", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpSkillApi.Models.ClientPost", b =>
                {
                    b.HasOne("UpSkillApi.Models.Client", "Client")
                        .WithMany("ClientPosts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.PostStatus", "PostStatus")
                        .WithMany("ClientPosts")
                        .HasForeignKey("PostStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.Profession", "Profession")
                        .WithMany()
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("PostStatus");

                    b.Navigation("Profession");
                });

            modelBuilder.Entity("UpSkillApi.Models.Organization", b =>
                {
                    b.HasOne("UpSkillApi.Models.User", "User")
                        .WithOne("Organization")
                        .HasForeignKey("UpSkillApi.Models.Organization", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpSkillApi.Models.PaidJob", b =>
                {
                    b.HasOne("UpSkillApi.Models.Organization", "Organization")
                        .WithMany("PaidJobs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.PostStatus", "PostStatus")
                        .WithMany("PaidJobs")
                        .HasForeignKey("PostStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PostStatus");
                });

            modelBuilder.Entity("UpSkillApi.Models.Rating", b =>
                {
                    b.HasOne("UpSkillApi.Models.Client", "Client")
                        .WithMany("Ratings")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.Worker", "Worker")
                        .WithMany("Ratings")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillApi.Models.VolunteeringApplication", b =>
                {
                    b.HasOne("UpSkillApi.Models.ApplicationStatus", "ApplicationStatus")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("ApplicationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.Client", "Client")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UpSkillApi.Models.VolunteeringJob", "VolunteeringJob")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("VolunteeringJobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.Worker", "Worker")
                        .WithMany("VolunteeringApplications")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApplicationStatus");

                    b.Navigation("Client");

                    b.Navigation("VolunteeringJob");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillApi.Models.VolunteeringJob", b =>
                {
                    b.HasOne("UpSkillApi.Models.Organization", "Organization")
                        .WithMany("VolunteeringJobs")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.PostStatus", "PostStatus")
                        .WithMany("VolunteeringJobs")
                        .HasForeignKey("PostStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PostStatus");
                });

            modelBuilder.Entity("UpSkillApi.Models.Worker", b =>
                {
                    b.HasOne("UpSkillApi.Models.Profession", "Profession")
                        .WithMany("Workers")
                        .HasForeignKey("ProfessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.User", "User")
                        .WithOne("Worker")
                        .HasForeignKey("UpSkillApi.Models.Worker", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Profession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UpSkillApi.Models.WorkerApplication", b =>
                {
                    b.HasOne("UpSkillApi.Models.ApplicationStatus", "ApplicationStatus")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("ApplicationStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("UpSkillApi.Models.ClientPost", "ClientPost")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("ClientPostId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UpSkillApi.Models.PaidJob", "PaidJob")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("PaidJobId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("UpSkillApi.Models.Worker", "Worker")
                        .WithMany("WorkerApplications")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ApplicationStatus");

                    b.Navigation("ClientPost");

                    b.Navigation("PaidJob");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillApi.Models.ApplicationStatus", b =>
                {
                    b.Navigation("VolunteeringApplications");

                    b.Navigation("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.Client", b =>
                {
                    b.Navigation("ClientPosts");

                    b.Navigation("Ratings");

                    b.Navigation("VolunteeringApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.ClientPost", b =>
                {
                    b.Navigation("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.Organization", b =>
                {
                    b.Navigation("PaidJobs");

                    b.Navigation("VolunteeringJobs");
                });

            modelBuilder.Entity("UpSkillApi.Models.PaidJob", b =>
                {
                    b.Navigation("WorkerApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.PostStatus", b =>
                {
                    b.Navigation("ClientPosts");

                    b.Navigation("PaidJobs");

                    b.Navigation("VolunteeringJobs");
                });

            modelBuilder.Entity("UpSkillApi.Models.Profession", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("UpSkillApi.Models.Sponsor", b =>
                {
                    b.Navigation("Advertisements");
                });

            modelBuilder.Entity("UpSkillApi.Models.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Organization");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("UpSkillApi.Models.VolunteeringJob", b =>
                {
                    b.Navigation("VolunteeringApplications");
                });

            modelBuilder.Entity("UpSkillApi.Models.Worker", b =>
                {
                    b.Navigation("Ratings");

                    b.Navigation("VolunteeringApplications");

                    b.Navigation("WorkerApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
